name: CI/CD for Streamlit App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or the version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # Ignore exit code 1 to not fail CI on minor issues
        flake8 . || true

    - name: Check formatting with black
      run: |
        pip install black
        black --check . || true

    - name: Run Streamlit app test (optional)
      run: |
        # Optional: run basic Streamlit check
        streamlit run app.py --server.headless true & sleep 10 && pkill streamlit
